### ISSUE TITLE
Research mobile app development tools

### ISSUE THREAD

**Issue by mfanor1** [Food-Oasis/HyperHex-Repo#10]
Look into which mobile app dev tools to use.

We will likely use Android Studio.

**Comment by minhaj98** [comment]
I think that we should stick to Android studio since we are all comfortable with using this IDE.

**Comment by monasterx3** [comment]
Here is the link to download Android Studios:
[https://developer.android.com/studio/index.html](url)


If you need help getting started here's a tutorial link. [https://www.javaworld.com/article/3340234/tutorial-series-android-studio-for-beginners.html](url)
